version: 2
jobs:
  build:
    docker:
      - image: alpine:3.8
    working_directory: /tmp/binsen
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: install tools
          command: |
            apk --no-cache --update add docker py-pip curl
            pip install docker-compose
      - run:
          name: build docker image
          no_output_timeout: 10m
          command: |
            docker build -f production.Dockerfile --rm=false -t nazo/binsen:latest .
      - run:
          name: boot backend process
          command: |
            docker-compose -p binsen -f .circleci/docker-compose.yml up -d
      - run:
          name: test
          command: |
            docker run -e CIRCLE_BRANCH=${CIRCLE_BRANCH} -e CIRCLE_SHA1=${CIRCLE_SHA1} -e CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM} -e CIRCLE_PULL_REQUEST=${CIRCLE_PULL_REQUEST} -e CODECOV_TOKEN=${CODECOV_TOKEN} --env-file=./.circleci/env --net=binsen_default -it nazo/binsen:latest /bin/bash /deploy/test.sh
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push nazo/binsen:latest
            fi
