// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	GooseDBVersion      string
	GroupUsers          string
	Groups              string
	MenuItems           string
	Notifications       string
	PostComments        string
	PostHistories       string
	PostLikes           string
	PostReads           string
	PostTemplates       string
	PostUploadFiles     string
	Posts               string
	PostsTags           string
	RolePermissions     string
	Roles               string
	Tags                string
	UserSigninHistories string
	UserTokens          string
	Users               string
	Workspaces          string
}{
	GooseDBVersion:      "goose_db_version",
	GroupUsers:          "group_users",
	Groups:              "groups",
	MenuItems:           "menu_items",
	Notifications:       "notifications",
	PostComments:        "post_comments",
	PostHistories:       "post_histories",
	PostLikes:           "post_likes",
	PostReads:           "post_reads",
	PostTemplates:       "post_templates",
	PostUploadFiles:     "post_upload_files",
	Posts:               "posts",
	PostsTags:           "posts_tags",
	RolePermissions:     "role_permissions",
	Roles:               "roles",
	Tags:                "tags",
	UserSigninHistories: "user_signin_histories",
	UserTokens:          "user_tokens",
	Users:               "users",
	Workspaces:          "workspaces",
}
